name: Run JSON Agent

on:
  workflow_dispatch:  # Allows manual execution
  push:
    branches:
      - main  # Runs when you push code to the main branch

jobs:
  run-agent:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Install Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.9"

      - name: Install Dependencies
        run: pip install requests

      - name: Run JSON Agent
        run: python agent.py
